### PR TITLE
First stab at adding extra info to Stripe

### PR DESCRIPTION
**Pull request by ghost**
Uses an extended user field to store the stripe customer ID
If this exists it retrieves the customer 
If not it creates a Stripe customer and saves the stripe ID back into the profile for future use

### CODE REVIEW

**Comment by Mark-H** [comment]
Hmm I'm working on merging this, but am I seeing correctly that it will always charge to the Customer record that was attached to the user, even if they entered a completely different card?

**Comment by studiorepublic** [comment]
That was the plan - not a good idea?

Kind regards,

Chris

Chris Todhunter
Director

Studio Republic
10 Charlecote Mews
Staple Gardens
Winchester
Hampshire
SO23 8SRW:www.studiorepublic.comT:+44 (0)1962 659123

Studio Republic is a trading name of Tin Roof Images Limited
Registered in England number: 5282012

**Comment by Mark-H** [comment]
I'm not sure - that sounds like an authorizations feature which we have on modmore.com where your card is stored on file, and later you have a one-click checkout where you don't fill in any details but it just gets charged to your account.

That's a cool feature worth having, but that's not fully implemented. Instead it is discarding the details the user entered, the token (which may be a completely different card because the old one expired or they simply want to pay from a different card). 

I thought the goal was simply to create a Customer record so the email would be visible in the Stripe dashboard and they could receive a receipt from stripe

**Comment by studiorepublic** [comment]
That was the goal originally, but when I was testing it out I ended up with
lots of duplicate customer records in Stripe which is why I saved the
customer token in MODX. If I was a store owner I think I'd want all
transactions from a customer saved together, regardless of the card they've
used. We're asking for new card details in the form rather than having a
save card details for later, though this would be a cool addition...

Kind regards,

Chris

Chris Todhunter
Director

Studio Republic
10 Charlecote Mews
Staple Gardens
Winchester
Hampshire
SO23 8SRW:www.studiorepublic.comT:+44 (0)1962 659123

Studio Republic is a trading name of Tin Roof Images Limited
Registered in England number: 5282012

**Comment by studiorepublic** [comment]
We will be closed from 12pm on the 23rd of December but will be back at our desks slightly fatter and fully rested on the 3rd of January     


10 Charlecote Mews, Staple Gardens, Winchester, Hampshire SO23 8SR

studiorepublic.com [https://www.studiorepublic.com]

Unsubscribe http://emails.studiorepublic.com/t/y-u-kljijyl-ttpjuiiuu-i/

**Pull request closed without merging**
